### ISSUE TITLE
don't get the data stream 

### ISSUE THREAD

**Issue by brammh** [dmamalis/apollopro_desktop#1]
Dear DMA,
I'm trying out your script to read my first degree apollo rower USB Serial interface. It's not a pro version (hybrid), but I hoped the USB serial interface was the same.
Both on a raspberry and on windows I'm able to open the relevant serial port. Though the Apollo is not 'spawning' data, only an initial data buffer when the screen is 'auto-enabled'.
Do I need to write something, to trigger a response? 
Understand you are not actively working on this script, hope you can put me in some direction though!
much appreciated!
bram

**Comment by brammh** [comment]
Figured out that if I send the /U /T /H /R etc commands first, it will trigger the data stream per stroke. issue can be closed. Thanks for sharing your code, very helpfull!

**Comment by dmamalis** [comment]
Hi brammh,
well I am glad you found a solution. Sorry for the late reply but this is a quite dead repo, however my apollo pro is still working and in case you use the code I would love to see what you can come up with.
